bigquery:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      schema: dbt_cody
      threads: 8
      project: dbt-test-env
      #execution_project: dbt-test-env
      dataproc_region: us-central1
      gcs_bucket: python-model-test
      dataproc_cluster_name: dbt-test-1
snowflake:
  target: dev
  outputs:
    dev:
      type: snowflake
      authenticator: externalbrowser
      account: ska67070
      database: analytics
      role: transformer
      schema: dbt_cody
      threads: 8
      user: cody.peterson@fishtownanalytics.com
      warehouse: transforming
    prod:
      type: snowflake
      authenticator: externalbrowser
      account: kw27752
      database: analytics
      role: transformer
      schema: dbt_cody
      threads: 8
      user: cody.peterson
      warehouse: transforming