bigquery:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      schema: dbt_cody
      threads: 8
      project: dbt-test-env
      #execution_project: dbt-test-env
      dataproc_region: us-central1
      gcs_bucket: python-model-test
      dataproc_cluster_name: dbt-test-1
databricks:
  target: dev
  outputs:
    dev:
      type: spark
      method: http
      schema: dbt_cody
      host: dbc-c7c89cba-cf9b.cloud.databricks.com
      token: "{{ env_var('SA_ADB_PAT') }}"
      cluster: 0830-163228-q22s4sv5
      # optional
      user: cody.peterson@dbtlabs.com
      connect_timeout: 60       # default 10
      connect_retries: 5        # default 0 
snowflake:
  target: dev
  outputs:
    dev:
      type: snowflake
      authenticator: externalbrowser
      account: ska67070
      database: analytics
      role: transformer
      schema: dbt_cody
      threads: 8
      user: cody.peterson@fishtownanalytics.com
      warehouse: transforming
    prod:
      type: snowflake
      authenticator: externalbrowser
      account: kw27752
      database: analytics
      role: transformer
      schema: dbt_cody
      threads: 8
      user: cody.peterson
      warehouse: transforming