[groups]
home = ["ym", "e", "c"]
usage = ["signups", "productusage", "docsusage", "basecamp", "posthog"]

[aliases]
a = "ascend"
adb = "azuredatabricks"
applocal = "ascendapplocal"
c = "cal"
chat = "copilot"
cloud = "digitalocean"
com = "community"
d = "drive"
dbx = "azuredatabricks"
do = "digitalocean"
docs = "ascenddocs"
e = "email"
eng = "engineering"
g = "github"
gh = "github"
i = "ibis"
incident = "incidents"
key = "keyboard"
ld = "launchdarkly"
md = "motherduck"
music = "youtubemusic"
p = "product"
prs = "pullrequests"
read = "kindle"
router = "mobilerouter"
s = "search"
snow = "snowflake"
static = "netlify"
travel = "navan"
y = "youtube"
ym = "youtubemusic"
z = "zulip"

[links]
admin = "https://api.app.ascend.io/admin/dashboard"
anthropic = "https://console.anthropic.com"
ascend = "https://ascend.io"
ascendapplocal = "https://instance.app.local.ascend.dev"
ascenddocs = "https://docs.ascend.io"
audible = "https://audible.com"
auth0 = "https://manage.auth0.com/dashboard/us/ascend-io-development/organizations/list"
aws = "https://us-east-2.console.aws.amazon.com/console"
azure = "https://portal.azure.com"
azuredatabricks = "https://adb-331203153589870.10.azuredatabricks.net"
backlog = "https://github.com/orgs/ascend-io/projects/6/views/23"
basecamp = "https://basecamp.app.ascend.io"
cal = "https://calendar.google.com"
claude = "https://claude.ai"
community = "https://github.com/orgs/ascend-io/projects/5"
copilot = "https://github.com/copilot"
databricks = "https://dbc-386e5cd3-1860.cloud.databricks.com"
demo = "https://demo.app.ascend.io"
digitalocean = "https://cloud.digitalocean.com"
dkdcdev = "https://dkdc.dev"
dkdcio = "https://dkdc.io"
docsusage = "https://analytics.google.com/analytics/web/?utm_source=marketingplatform.google.com&utm_medium=et&utm_campaign=marketingplatform.google.com%2Fabout%2Fanalytics%2F#/a70090768p454536018/reports/intelligenthome"
drive = "https://drive.google.com"
ducklake = "https://ducklake.select"
edge = "/Applications/Microsoft Edge.app"
email = "https://mail.google.com"
engineering = "https://github.com/orgs/ascend-io/projects/6"
everyone = "https://github.com/orgs/ascend-io/projects/6/views/53"
expense = "https://www.expensify.com/inbox"
fabric = "https://app.fabric.microsoft.com"
feedback = "https://github.com/orgs/ascend-io/projects/12/views/1"
figma = "https://www.figma.com/design/ElQAgiApiPg1aBfEV4QHCn/Ascend-UI?node-id=4739-56728&t=TGeJiy17DcjSt7rE-0"
foundry = "https://ai.azure.com/nextgen/r/N7JX_HUZTTy4llGorGlftA,ase-dev,,development-eastus2-resource,development-eastus2/home"
gcp = "https://console.cloud.google.com"
github = "https://github.com"
godocs = "https://go.dev/doc"
gusto = "https://app.gusto.com"
hetzner = "https://konsoleh.hetzner.com"
ibis = "https://ibis-project.org"
inbox = "https://github.com/orgs/ascend-io/projects/6/views/10"
incidents = "https://ascendio.grafana.net/a/grafana-irm-app/incidents?q=state%3Aactive"
keyboard = "https://configure.zsa.io/moonlander"
kindle = "https://read.amazon.com"
launchdarkly = "https://app.launchdarkly.com/projects/inception/flags?env=production&env=production&selected-env=production"
lunch = "https://forkable.com/mc"
me = "https://github.com/orgs/ascend-io/projects/6/views/24"
miro = "https://miro.com/app/dashboard"
mobilerouter = "http://192.168.8.1"
motherduck = "https://app.motherduck.com"
navan = "https://app.navan.com"
netlify = "https://app.netlify.com"
openai = "https://platform.openai.com/docs/overview"
posthog = "https://us.posthog.com/project/282621"
product = "https://github.com/ascend-io/product"
product_dev = "https://product.app-dev.ascend.io"
productusage = "https://lookerstudio.google.com/u/0/reporting/ea744630-ba35-4244-9314-9122d52cadfa/page/BJhZF"
pullrequests = "https://github.com/pulls"
rustbook = "https://doc.rust-lang.org/book"
search = "https://google.com"
signups = "https://app-na2.hubspot.com/contacts/7088968/objectLists/4638/filters"
snowflake = "https://app.snowflake.com"
youtube = "https://youtube.com"
youtubemusic = "https://music.youtube.com"
zulip = "/Applications/Zulip.app"
